using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TestCorou : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        StartCoroutine(MakeBullet());
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    IEnumerator MakeBullet()
    {
        Debug.Log("총알발사");
        while (true)
        {
            yield return new WaitForSeconds(0.2f);
            Debug.Log("탕!"); //볼륨 -= 0.01f
        }
    }

    IEnumerator Test()
    {
        Debug.Log("장전");

        while (true)
        {
            yield return new WaitForSeconds(1);
            Debug.Log("발사");
        }
    }

}
